FILE_LIST = 'file_list_5fold.pkl'
ANNOTATION_PATH = 'k400_all.pkl'
TEST_ANNOTATION_PATH = 'test_len.json'
DATA_PATH = '/workspace/LOVEU/data/LOVEU_both_hr_padded/train_val/'
DATA_PATH_2 = '/workspace/LOVEU/data/LOVEU_both_hr/train_val/'
TEST_DATA_PATH = '/workspace/LOVEU/data/LOVEU_both_hr_padded/test/'
PRED_PATH = 'k400_pred.pkl'
VISUAL_DATA_PATH = './visualizing/'
MODEL_SAVE_PATH = './models/'

FEATURE_DIM = 2304 + 4096
FEATURE_DIM_1 = 2304
FEATURE_DIM_2 = 4096

FEATURE_LEN = 40
TIME_UNIT = 0.25

GAP = 16
CHANNEL_NUM = 4
ENCODER_HIDDEN = 512
DECODER_HIDDEN = 128
EVENT_LOSS_COEF = 0.5
SHOT_LOSS_COEF = 0.2
WHOLE_LOSS_COEF = 0.3
AUX_LOSS_COEF = 0.5
ENTROPY_LOSS_COEF = 0.

BATCH_SIZE = 128
LEARNING_RATE = 1e-4
RANDOM_CHOICE_PROB_START = 1.
RANDOM_CHOICE_PROB_END = 0.
RANDOM_CHOICE_PROB_DELTA = -0.0

GLUE_PROB = 0.25
INTERPOLATION_PROB = 0.2

DEVICE = 'cuda'

THRESHOLD = 0.1
VAL_VIDEOS = ["hlm7ShpS1z0", "jw1kPjGu1YE", "u959kyRLWdQ", "z1-T4zHXvSY", "z1-U0uYFY3Q"]
SIGMA_LIST = [0.1, 0.4,]
TEST_THRESHOLD = 0.8095
GOAL_SCORE = 0.817

PATIENCE = 7

NUM_WORKERS = 4
